protection:
  default-minutes: 2
  first-join-minutes: 2
  protection-display: actionbar # Possible values: actionbar, bossbar
  restart-when-dying: false # When a player dies with protection if it should restart
  continue-offline: false

claim: # A player can claim spawnprotection once per day
  enabled: true
  duration: 30 # In minutes
  required-online-minutes: 15 #Requiered online minutes to claim spawnprotection

proximity-detection:
  radius: 52
  min-time-seconds: 120

messages:
  protection-ended: "&aYour spawn protection has ended."
  protected-nearby: "&eYou are too close to players who could harm you!"
  aggressor-nearby: "&cDo not chase spawn protected players!"