protection:
  default-minutes: 2
  first-join-minutes: 2
  protection-display: actionbar # Mögliche Werte: actionbar, bossbar

claim:
  enabled: true
  duration: 30 # in minutes
  required-online-minutes: 15
  offline-countdown: false # true = Timer läuft auch wenn Spieler offline ist

proximity-detection:
  radius: 52
  min-time-seconds: 120

messages:
  protection-ended: "&aYour spawn protection has ended."
  protected-nearby: "&eYou are too close to players who could harm you!"
  aggressor-nearby: "&cDo not chase spawn protected players!"
