name: SpawnProtection
version: '1.0'
main: de.nikey.spawnProtection.SpawnProtection
api-version: '1.21'
authors: [ Nikey ]
website: https://github.com/NikeyV1
commands:
  confirmattack:
    description: Confirm attacking a protected player
  endprotection:
    description: End your spawn protection manually